INSERT INTO technologies (name, kind, license, tags_csv, github_url, documentation_url, description,
                          last_updated, language, runtime, serverless_friendly, supports_ssr, db_model_type,
                          mobile_platform,
                          performance_score, scalability_score, maintainability_score, security_score,
                          cost_effectiveness_score, community_support_score, ecosystem_maturity_score,
                          vendor_lockin_score)
VALUES ('Spring Boot',
        'BACKEND',
        'APACHE_2_0',
        'backend,java,spring',
        'https://github.com/spring-projects/spring-boot',
        'https://docs.spring.io/spring-boot/',
        'Popular Java backend framework',
        NOW(),
        'JAVA',
        'JDK',
        true,
        NULL,
        NULL,
        NULL,
        0.8, 0.9, 0.7, 0.8,
        0.6, 0.9, 0.8, 0.5),
       ('Express.js',
        'BACKEND',
        'MIT',
        'backend,nodejs,javascript,express,rest',
        'https://github.com/expressjs/express',
        'https://expressjs.com/',
        'Minimal and flexible Node.js web application framework',
        NOW(),
        'JAVASCRIPT',
        'NODE',
        true,
        NULL,
        NULL,
        NULL,
        0.75, 0.8, 0.8, 0.7,
        0.85, 0.85, 0.8, 0.15),
       ('FastAPI',
        'BACKEND',
        'MIT',
        'backend,python,fastapi,rest,openapi,async',
        'https://github.com/fastapi/fastapi',
        'https://fastapi.tiangolo.com/',
        'Modern, high-performance Python web framework for building APIs (ASGI, type hints, OpenAPI)',
        NOW(),
        'PYTHON',
        'PYTHON_RUNTIME',
        true,
        NULL,
        NULL,
        NULL,
        0.85, 0.8, 0.8, 0.8,
        0.85, 0.8, 0.75, 0.1),

       ('ASP.NET Core',
        'BACKEND',
        'MIT',
        'backend,csharp,dotnet,aspnetcore,rest,minimal-api,mvc',
        'https://github.com/dotnet/aspnetcore',
        'https://learn.microsoft.com/aspnet/core/?view=aspnetcore-10.0',
        'Open-source, cross-platform .NET framework for building web apps and APIs',
        NOW(),
        'CSHARP',
        'DOTNET',
        true,
        true,
        NULL,
        NULL,
        0.8, 0.82, 0.85, 0.9,
        0.75, 0.9, 0.9, 0.35),
       ('React',
        'FRONTEND',
        'MIT',
        'frontend,javascript,react',
        'https://github.com/facebook/react',
        'https://react.dev',
        'Leading frontend UI framework',
        NOW(),
        'JAVASCRIPT',
        'NODE',
        true,
        true,
        NULL,
        NULL,
        0.7, 0.8, 0.7, 0.7,
        0.5, 0.8, 0.7, 0.4),
       ('Angular',
        'FRONTEND',
        'MIT',
        'frontend,typescript,angular,spa',
        'https://github.com/angular/angular',
        'https://angular.dev/overview',
        'Full-featured TypeScript-based frontend framework',
        NOW(),
        'TYPESCRIPT',
        'NODE',
        true,
        true,
        NULL,
        NULL,
        0.75, 0.85, 0.8, 0.85,
        0.75, 0.85, 0.9, 0.25),
       ('PostgreSQL',
        'DATABASE',
        'OPEN_SOURCE',
        'database,postgresql,sql,relational',
        'https://github.com/postgres/postgres',
        'https://www.postgresql.org/docs/',
        'Popular open-source relational database',
        NOW(),
        NULL,
        'NATIVE',
        true,
        NULL,
        'RELATIONAL',
        NULL,
        0.9, 0.85, 0.9, 0.95,
        0.85, 0.95, 0.9, 0.1),
       ('MongoDB',
        'DATABASE',
        'OPEN_SOURCE',
        'database,mongodb,nosql,document',
        'https://github.com/mongodb/mongo',
        'https://www.mongodb.com/docs/',
        'Popular document-oriented NoSQL database',
        NOW(),
        NULL,
        'NATIVE',
        true,
        NULL,
        'DOCUMENT',
        NULL,
        0.8, 0.9, 0.8, 0.75,
        0.8, 0.9, 0.85, 0.2),
       ('Flutter',
        'MOBILE',
        'OPEN_SOURCE',
        'mobile,flutter,dart,cross-platform',
        'https://github.com/flutter/flutter',
        'https://docs.flutter.dev',
        'Cross-platform mobile UI framework by Google',
        NOW(),
        'DART',
        'NATIVE',
        true,
        true,
        NULL,
        'IOS_AND_ANDROID',
        0.85, 0.8, 0.8, 0.75,
        0.9, 0.9, 0.85, 0.2),
       ('React Native',
        'MOBILE',
        'MIT',
        'mobile,react-native,javascript,cross-platform',
        'https://github.com/facebook/react-native',
        'https://reactnative.dev',
        'Cross-platform mobile framework based on React',
        NOW(),
        'JAVASCRIPT',
        'NATIVE',
        true,
        true,
        NULL,
        'IOS_AND_ANDROID',
        0.8, 0.75, 0.8, 0.7,
        0.85, 0.9, 0.85, 0.15);
