INSERT INTO technologies (id, name, kind, license, tags_csv, github_url, documentation_url, description,
                          last_updated, language, runtime, db_model_type, mobile_platform,
                          performance_score, scalability_score, maintainability_score, security_score,
                          cost_effectiveness_score, community_support_score, ecosystem_maturity_score,
                          vendor_lockin_score)
VALUES (1,
        'Spring Boot',
        'BACKEND',
        'APACHE_2_0',
        'backend,java,spring',
        'https://github.com/spring-projects/spring-boot',
        'https://docs.spring.io/spring-boot/',
        'Popular Java backend framework',
        NOW(),
        'JAVA',
        'JDK',
        NULL,
        NULL,
        0.8, 0.9, 0.7, 0.8,
        0.6, 0.9, 0.8, 0.5),
       (2,
        'React',
        'FRONTEND',
        'MIT',
        'frontend,javascript,react',
        'https://github.com/facebook/react',
        'https://react.dev',
        'Leading frontend UI framework',
        NOW(),
        'JAVASCRIPT',
        'NODE',
        NULL,
        NULL,
        0.7, 0.8, 0.7, 0.7,
        0.5, 0.8, 0.7, 0.4);
